--- English game strings.

return {
    MAIN_MENU_TITLE = 'BOOM',
    MAIN_MENU_OPTIONS = 'OPTIONS',
    MAIN_MENU_NEW = 'NEW GAME',
    MAIN_MENU_CONTINUE = 'CONTINUE GAME',
    MAIN_MENU_LOAD = 'CONTINUE',
    MAIN_MENU_QUIT = 'QUIT',
    OPTIONS_MENU_MODE = 'MODE: ',
    OPTIONS_MENU_VSYNC = 'VSYNC: ',
    OPTIONS_MENU_MSAA = 'MSAA: ',
    OPTIONS_MENU_OK = 'OK',
    OPTIONS_MENU_CANCEL = 'CANCEL',
    CONFIRM_MENU_TITLE = 'KEEP CHANGES?',
    CONFIRM_MENU_OK = 'YES',
    CONFIRM_MENU_CANCEL = 'NO',
    CONFIRM = 'OK',
    CANCEL = 'CANCEL',
}
